import streamlit as st
from components import navbar, sidebar, tables
from utils import require_auth
import db

def render():
    require_auth()
    navbar.render()
    sidebar.render()
    
    st.title("📋 Security Event Logs")
    st.markdown("Comprehensive view of all security events and detections")
    
    st.markdown("---")
    
    col1, col2, col3 = st.columns([2, 2, 2])
    
    with col1:
        log_limit = st.selectbox("Entries per page:", [25, 50, 100, 250, 500], index=2, key="logs_limit")
    
    with col2:
        filter_action = st.selectbox("Filter by action:", ["All", "blocked", "allowed"], key="logs_filter_action")
    
    with col3:
        filter_label = st.selectbox("Filter by label:", ["All", "attack", "normal"], key="logs_filter_label")
    
    st.markdown("---")
    
    logs = db.get_logs(limit=log_limit)
    
    if filter_action != "All":
        logs = [log for log in logs if log.get('action') == filter_action]
    
    if filter_label != "All":
        logs = [log for log in logs if log.get('label') == filter_label]
    
    st.markdown(f"### Showing {len(logs)} events")
    
    if logs:
        tables.render_logs_table(logs, limit=log_limit)
        
        st.markdown("---")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            total = len(logs)
            st.metric("Total Events", total)
        
        with col2:
            blocked = len([log for log in logs if log.get('action') == 'blocked'])
            st.metric("Blocked", blocked)
        
        with col3:
            if total > 0:
                avg_confidence = sum([log.get('confidence', 0) for log in logs]) / total
                st.metric("Avg Confidence", f"{avg_confidence:.2f}")
            else:
                st.metric("Avg Confidence", "0.00")
    else:
        st.info("No logs match the selected filters")
    
    st.markdown("---")
    
    if st.button("🔄 Refresh Logs", key="refresh_logs", use_container_width=True):
        st.rerun()
    
    st.markdown("---")
    
    st.markdown("""
    <div style='background: rgba(59, 130, 246, 0.1); border: 1px solid #3b82f6; 
                border-radius: 8px; padding: 16px;'>
        <h4 style='color: #3b82f6; margin-bottom: 8px;'>ℹ️ About Security Logs</h4>
        <p style='color: #a0aec0; font-size: 14px;'>
            Security logs are generated by the AI detection engine monitoring network traffic.
            Each entry includes the source IP, detection label, confidence score, and action taken.
            High confidence scores indicate strong certainty in the threat classification.
        </p>
    </div>
    """, unsafe_allow_html=True)